"""empty message

Revision ID: 0b093bec7932
Revises: 96ba13148fbf
Create Date: 2017-11-25 21:37:06.048057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b093bec7932'
down_revision = '96ba13148fbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flask_user', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flask_user', 'confirmed')
    # ### end Alembic commands ###
