"""empty message

Revision ID: 1b923e57ecb1
Revises: 9e4188cb2bb5
Create Date: 2017-11-21 00:16:24.336745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b923e57ecb1'
down_revision = '9e4188cb2bb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('question_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comment', 'question', ['question_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_column('comment', 'question_id')
    # ### end Alembic commands ###
