"""empty message

Revision ID: 96ba13148fbf
Revises: 1b923e57ecb1
Create Date: 2017-11-21 23:41:45.513155

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '96ba13148fbf'
down_revision = '1b923e57ecb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('create_time', sa.DateTime(), nullable=True))
    op.alter_column('comment', 'author_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('comment', 'question_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comment', 'question_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('comment', 'author_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_column('comment', 'create_time')
    # ### end Alembic commands ###
