"""empty message

Revision ID: 9e4188cb2bb5
Revises: bc564eadf8b4
Create Date: 2017-11-21 00:14:25.614063

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9e4188cb2bb5'
down_revision = 'bc564eadf8b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comment_ibfk_1', 'comment', type_='foreignkey')
    op.drop_column('comment', 'question_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('question_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('comment_ibfk_1', 'comment', 'question', ['question_id'], ['id'])
    # ### end Alembic commands ###
