"""empty message

Revision ID: bc564eadf8b4
Revises: ea00cb953c97
Create Date: 2017-11-21 00:13:04.634362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc564eadf8b4'
down_revision = 'ea00cb953c97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('author_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comment', 'flask_user', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_column('comment', 'author_id')
    # ### end Alembic commands ###
