"""empty message

Revision ID: d23a83476374
Revises: 705e1d21c5c4
Create Date: 2017-11-12 22:28:27.317130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd23a83476374'
down_revision = '705e1d21c5c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flask_user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('phone', sa.String(length=11), nullable=False),
    sa.Column('user', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flask_user')
    # ### end Alembic commands ###
