# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 23:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20171214_2235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='expert',
            new_name='excerpt',
        ),
    ]
